name: Build and Publish Docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto-increment major version
        id: version
        run: |
          # Start at 1.0.0 if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # Extract version components
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Increment major version
          NEW_MAJOR=$((MAJOR + 1))
          NEW_VERSION="v$NEW_MAJOR.0.0"
          echo "New version: $NEW_VERSION"
          
          # Set output
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version_without_v=${NEW_VERSION#v}" >> $GITHUB_OUTPUT
          
          # Create and push new tag
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $NEW_VERSION -m "Auto-incremented version to $NEW_VERSION"
          git push origin $NEW_VERSION

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            siva27neelam/story-telling:${{ steps.version.outputs.version_without_v }}
            siva27neelam/story-telling:latest